### ISSUE TITLE
Use YAML manifest for loading persistence data

### ISSUE THREAD

**Issue by iromli** [GluuFederation/community-edition-containers#12]
Currently, persistence *job* is loaded by calling Docker API [directly](https://github.com/GluuFederation/community-edition-containers/blob/b1abec3b9f288e49199e9b3df9856c4555a3ab8d/pygluu-compose/pygluu/compose/app.py#L546) (with `PERSISTENCE_VERSION` settings) adds difficulties on running the *job* for other versions (without changing `settings.py`). For example, latest v1.2.1 defines `PERSISTENCE_VERSION=4.2.0_01` which it will load data for v4.2; there's no easy option to run it for v4.1. By moving the process to a YAML manifest, the version can be overriden in `docker-compose.override.yaml`.

For illustration:

```yaml
# svc.persistence.yml
version: "2.4"
services:
  persistence:
    image: gluufederation/persistence:4.2.0_01
```

can be overriden in `docker-compose.override.yml`:

```yaml
# docker-compose.override.yml
version: "2.4"
services:
  persistence:
    image: gluufederation/persistence:4.2.1_dev
```

Things to consider:

- persistence is a one-time job
- running persistence should be idempotent
